//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNG8_Api.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KNG8_ProjectEntities : DbContext
    {
        public KNG8_ProjectEntities()
            : base("name=KNG8_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BITACORA> BITACORAs { get; set; }
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<Correo> Correos { get; set; }
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<Expediente> Expedientes { get; set; }
        public virtual DbSet<Odontograma> Odontogramas { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TiposCita> TiposCitas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    
        public virtual ObjectResult<Consultar_Datos_Usuario_Result> Consultar_Datos_Usuario(string correo, string contrasenna)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contrasennaParameter = contrasenna != null ?
                new ObjectParameter("Contrasenna", contrasenna) :
                new ObjectParameter("Contrasenna", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consultar_Datos_Usuario_Result>("Consultar_Datos_Usuario", correoParameter, contrasennaParameter);
        }
    
        public virtual int Registrar_Bitacora(string correo, Nullable<System.DateTime> fechaHora, Nullable<int> codigoError, string descripcion, string origen)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var fechaHoraParameter = fechaHora.HasValue ?
                new ObjectParameter("FechaHora", fechaHora) :
                new ObjectParameter("FechaHora", typeof(System.DateTime));
    
            var codigoErrorParameter = codigoError.HasValue ?
                new ObjectParameter("CodigoError", codigoError) :
                new ObjectParameter("CodigoError", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var origenParameter = origen != null ?
                new ObjectParameter("Origen", origen) :
                new ObjectParameter("Origen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_Bitacora", correoParameter, fechaHoraParameter, codigoErrorParameter, descripcionParameter, origenParameter);
        }
    
        public virtual int Registrar_Correo(string to, Nullable<long> consecutivoUsuario, Nullable<System.DateTime> fechaHora, string cC, string body, string subject)
        {
            var toParameter = to != null ?
                new ObjectParameter("To", to) :
                new ObjectParameter("To", typeof(string));
    
            var consecutivoUsuarioParameter = consecutivoUsuario.HasValue ?
                new ObjectParameter("ConsecutivoUsuario", consecutivoUsuario) :
                new ObjectParameter("ConsecutivoUsuario", typeof(long));
    
            var fechaHoraParameter = fechaHora.HasValue ?
                new ObjectParameter("FechaHora", fechaHora) :
                new ObjectParameter("FechaHora", typeof(System.DateTime));
    
            var cCParameter = cC != null ?
                new ObjectParameter("CC", cC) :
                new ObjectParameter("CC", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("Body", body) :
                new ObjectParameter("Body", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("Subject", subject) :
                new ObjectParameter("Subject", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Registrar_Correo", toParameter, consecutivoUsuarioParameter, fechaHoraParameter, cCParameter, bodyParameter, subjectParameter);
        }
    
        public virtual ObjectResult<SelectAllErrors_Result> SelectAllErrors()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllErrors_Result>("SelectAllErrors");
        }
    
        public virtual ObjectResult<SelectAllRoles_Result> SelectAllRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllRoles_Result>("SelectAllRoles");
        }
    
        public virtual ObjectResult<SelectAllTiposCitas_Result> SelectAllTiposCitas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllTiposCitas_Result>("SelectAllTiposCitas");
        }
    
        public virtual ObjectResult<SelectAllUsers_Result> SelectAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllUsers_Result>("SelectAllUsers");
        }
    
        public virtual ObjectResult<SelectUsersDescription_Result> SelectUsersDescription()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectUsersDescription_Result>("SelectUsersDescription");
        }
    }
}
