//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNG8_Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odontograma
    {
        public int OdontogramaID { get; set; }
        public int ConsecutivoUsuario { get; set; }
        public int NDiente { get; set; }
        public Nullable<int> CoordenadaUno { get; set; }
        public Nullable<int> CoordenadaDos { get; set; }
        public Nullable<int> CoordenadaTres { get; set; }
        public Nullable<int> CoordenadaCuatro { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
