//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNG8_Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposCita
    {
        public int TipoID { get; set; }
        public string DescripcionTiposCitas { get; set; }
    
        public virtual Cita Cita { get; set; }
    }
}
