//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNG8_Api.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.BITACORAs = new HashSet<BITACORA>();
            this.Citas = new HashSet<Cita>();
            this.Expedientes = new HashSet<Expediente>();
            this.Odontogramas = new HashSet<Odontograma>();
        }
    
        public int ConsecutivoUsuario { get; set; }
        public string NombreCompleto { get; set; }
        public int Cedula { get; set; }
        public string Correo { get; set; }
        public string Contrasenna { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int Telefono { get; set; }
        public int RoleID { get; set; }
        public int EstadoID { get; set; }
        public int ErrorID { get; set; }
        public Nullable<int> ExpedienteID { get; set; }
        public Nullable<int> CitaID { get; set; }
        public Nullable<int> OdontogramaID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BITACORA> BITACORAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Citas { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expediente> Expedientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odontograma> Odontogramas { get; set; }
        public virtual Role Role { get; set; }
    }
}
